@url = http://localhost:3001/api/blogs

###
GET {{url}}

### POST WITH LIKES
POST {{url}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWQiOiI2NmQ3YzQxNGRlODRjZDg4MmJjNDljMTgiLCJpYXQiOjE3MjU2NDUzODgsImV4cCI6MTcyNTY0ODk4OH0.ciVObmjodQLBFZSbLB-aWVGOTR_VNdx0CBE_DLp5peY

{
  "title": "Humans and mutants together",
  "author": "Charles Xavier",
  "url": "http://wwww.xmen.com",
  "likes": 10
}

### POST WITHOUT LIKES
POST {{url}}
Content-Type: application/json

{
  "title": "Humans down",
  "author": "Magneto",
  "url": "http://wwww.magneto.com",
}

### 
DELETE {{url}}/66da3ba158c19b54b33429ae
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWQiOiI2NmQ3YzQxNGRlODRjZDg4MmJjNDljMTgiLCJpYXQiOjE3MjU2NDUzODgsImV4cCI6MTcyNTY0ODk4OH0.ciVObmjodQLBFZSbLB-aWVGOTR_VNdx0CBE_DLp5peY