@url = http://localhost:3001/api/persons
#@url = "https://ycm-fullstack-part3-backend.fly.dev/api/persons"

GET {{url}}

###
GET {{url}}/6623f0bbaeb91a65e1d22ae3

###
GET {{url}}/2

###
DELETE {{url}}/6623f0bbaeb91a65e1d22ae3

###
POST {{url}}
Content-Type: application/json

{
  "name": "Angel DiMaria",
  "number": "33-323423-234234"
}

###
PUT {{url}}/6623f070a89a0a3418113a7e
Content-Type: application/json

{
  "name": "Angel DiMaria",
  "number": "55-5555-5555"
}

### 
POST {{url}}
Content-Type: application/json


